### ISSUE TITLE
Support deleting tweets and DMs

### ISSUE THREAD

**Issue by micahflee** [lockdown-systems/cyd#13]
- [x] support deleting tweets #79 
- [x] support archiving likes #81 
- [x] support deleting likes #82
- [x] when you index tweets or likes, and check "re-index", it should start counting over in the progress #83
- [x] when you index tweets or likes, it should only index the latest by default (right now it's scrolling to the bottom) #84
- [x] when you archive tweets, it should not redownload tweets if the HTML file is already there #85
- [x] support deleting retweets #86
- [x] support deleting DMs #87
